image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup & Run Flutter Web
    init: flutter pub get
    command: flutter run -d web-server --web-port=3000 --release

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
