image:
  file: .gitpod.dockerfile

tasks:
  - name: Set up Flutter Web
    init: flutter pub get
    command: flutter run -d chrome --web-port=3000

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
